Repository webpack-contrib/worker-loader, pull requests merged in 2018-02, with the labels that each got.

#128 fix(index): add `webpack >= v4.0.0` support
  src/index.js
Labels: priority: 2 (urgent), semver: Patch, severity: 2 (regression), status: Pending, type: Bug

#130 fix(package): homepage URL typo
  package.json
Labels: semver: Patch, status: Approved, type: Bug

#131 docs(README): add note about omitted hashes (`options.name`)
  README.md
Labels: semver: Patch, status: Approved, type: Documentation
